---
# main playbook to call roles

- name: Implement postfix fail2ban rule
  hosts: server1
  gather_facts: false
  roles:
    - create_filter
  vars:
    - filter_conf: postfix_unknown.conf
    - filter_regex: "^.* postfix/smtpd\\[.*\\]: connect from unknown\\[<HOST>\\]$"
    - create: false
    - test_it: true
    - log_file_to_check: /var/log/syslog
    
- name: Apply postfix fail2ban rule to jail conf
  hosts: server1
  gather_facts: false
  roles:
    - append_to_jail
  vars:
    - jail_conf_file: jail.conf
    - log_file_to_check: /var/log/syslog
    - filter_name: postfix_unknown
    - create: false
    - test_it: true

- name: Implement postfix sas login fail2ban rule
  hosts: server1
  gather_facts: false
  roles:
    - create_filter
  vars:
    - filter_conf: postfix_sas.conf
    - filter_regex: ".*\\[<HOST>\\]: SASL LOGIN authentication failed: generic failure$"
    - create: false
    - test_it: true
    - log_file_to_check: /var/log/syslog
    
- name: Apply postfix sas login fail2ban rule to jail conf
  hosts: server1
  gather_facts: false
  roles:
    - append_to_jail
  vars:
    - jail_conf_file: jail.conf
    - log_file_to_check: /var/log/syslog
    - filter_name: postfix_sas
    - create: false
    - test_it: true
     
- name: Implement postfix RCPT from unknown fail2ban rule
  hosts: server1
  gather_facts: false
  roles:
    - create_filter
  vars:
    - filter_conf: postfix_rcpt.conf
    - filter_regex: ".* postfix/smtpd\\[.*\\]: NOQUEUE: reject: RCPT from unknown\\[<HOST>\\]"
    - create: false
    - test_it: true
    - log_file_to_check: /var/log/syslog
    
- name: Apply postfix RCPT from unknown fail2ban rule to jail conf
  hosts: server1
  gather_facts: false
  roles:
    - append_to_jail
  vars:
    - jail_conf_file: jail.conf
    - log_file_to_check: /var/log/syslog
    - filter_name: postfix_rcpt
    - create: false
    - test_it: true
  
- name: Implement named query (cache) denied fail2ban rule
  hosts: server1
  gather_facts: false
  roles:
    - create_filter
  vars:
    - filter_conf: named_cache.conf
    - filter_regex: "named\\[.*\\]: client <HOST>#.* \\(.*\\): query \\(cache\\)"
    - create: false
    - test_it: true
    - log_file_to_check: /var/log/syslog
    
- name: Apply named query (cache) denied fail2ban rule to jail conf
  hosts: server1
  gather_facts: false
  roles:
    - append_to_jail
  vars:
    - jail_conf_file: jail.conf
    - log_file_to_check: /var/log/syslog
    - filter_name: named_cache
    - create: false
    - test_it: true
    
- name: Implement pop3d LOGIN FAILED fail2ban rule
  hosts: server1
  gather_facts: false
  roles:
    - create_filter
  vars:
    - filter_conf: pop3d_login.conf
    - filter_regex: "pop3d: LOGIN FAILED, .*, ip=\\[::ffff:<HOST>\\]$"
    - create: false
    - test_it: true
    - log_file_to_check: /var/log/syslog
    
- name: Apply pop3d LOGIN FAILED fail2ban rule to jail conf
  hosts: server1
  gather_facts: false
  roles:
    - append_to_jail
  vars:
    - jail_conf_file: jail.conf
    - log_file_to_check: /var/log/syslog
    - filter_name: pop3d_login
    - create: false
    - test_it: true
    
- name: Implement proftpd - FTP session closed fail2ban rule
  hosts: server1
  gather_facts: false
  roles:
    - create_filter
  vars:
    - filter_conf: proftpd_closed.conf
    - filter_regex: "proftpd\\[.*\\]: .* \\(.*\\[<HOST>\\]\\) \\- FTP session closed\\.$"
    - create: false
    - test_it: true
    - log_file_to_check: /var/log/syslog
    
- name: Apply proftpd - FTP session closed fail2ban rule to jail conf
  hosts: server1
  gather_facts: false
  roles:
    - append_to_jail
  vars:
    - jail_conf_file: jail.conf
    - log_file_to_check: /var/log/syslog
    - filter_name: proftpd_closed
    - create: false
    - test_it: true
 
- name: Implement postfix anvil statistics max connection count fail2ban rule
  hosts: server1
  gather_facts: false
  roles:
    - create_filter
  vars:
    - filter_conf: postfix_anvil.conf
    - filter_regex: "postfix/anvil\\[.*\\]: statistics: max connection count .* for \\(smtp:<HOST>\\) at.*"
    - create: true
    - test_it: true
    - log_file_to_check: /var/log/syslog
    
- name: Apply postfix anvil statistics max connection count fail2ban rule to jail conf
  hosts: server1
  gather_facts: false
  roles:
    - append_to_jail
  vars:
    - jail_conf_file: jail.conf
    - log_file_to_check: /var/log/syslog
    - filter_name: postfix_anvil
    - create: false
    - test_it: true
    
- name: Apply new date parser for multics
  hosts: server1
  gather_facts: false
  roles:
    - fail2ban_regex_date
  vars:
    - create: true
    - test_it: true
...