---
# defaults file for roles/append_to_jail

fail2ban_conf_path: /etc/fail2ban
jail_conf_rule_content: "{{ lookup('template', 'jail.conf.j2', template_vars=dict(name=filter_name, log_file=log_file_to_check)) }}"